name: intime
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0

  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.10.0
  permission_handler: ^11.3.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  image: ^4.7.2
  tflite_flutter: ^0.12.1
  http: ^1.6.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  cached_network_image: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
